fixed playwright.yml

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -95,26 +95,28 @@ jobs:
         retention-days: 30
 
     # Пуш звіту до іншої гілки репозиторію
-    - name: Push Allure report to branch
-      run: |
-        git config --global user.email "tkachuky105@gmail.com"
-        git config --global user.name "Tkachuk-Yaroslav"
-        git fetch origin gh-pages || true
-        if git show-ref --quiet refs/heads/gh-pages; then
-          git checkout gh-pages
-        else
-          git checkout -b gh-pages
-        fi
-        cp -R allure-report/* .
-        git add .
-        git commit -m "Update Allure report" || echo "No changes to commit"
-        git push origin gh-pages --force || echo "Failed to push to gh-pages branch"
+- name: Push Allure report to branch
+  env:
+    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  run: |
+    git config --global user.email "tkachuky105@gmail.com"
+    git config --global user.name "Tkachuk-Yaroslav"
+    git fetch origin gh-pages || true
+    if git show-ref --quiet refs/heads/gh-pages; then
+      git checkout gh-pages
+    else
+      git checkout -b gh-pages
+    fi
+    cp -R allure-report/* .
+    git add .
+    git commit -m "Update Allure report" || echo "No changes to commit"
+    git push https://x-access-token:${GITHUB_TOKEN}@github.com/Tkachuk-Yaroslav/intership_aqa_js_2.git gh-pages --force || echo "Failed to push to gh-pages branch"
 
     # Додавання посилання на GitHub Pages у опис
-    - name: Add GitHub Pages link to description
-      run: |
-        echo "Allure Report: https://Tkachuk-Yaroslav.github.io/intership_aqa_js_2/" >> README.md
-        git add README2.md
-        git commit -m "Add GitHub Pages link to README" || echo "No changes to commit"
-        git push origin main || echo "Failed to push changes to main branch"
+- name: Add GitHub Pages link to description
+  run: |
+    echo "Allure Report: https://Tkachuk-Yaroslav.github.io/intership_aqa_js_2/" >> README.md
+    git add README.md
+    git commit -m "Add GitHub Pages link to README" || echo "No changes to commit"
+    git push origin main || echo "Failed to push changes to main branch"
 
